#line 2 "lex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
static yyconst short int yy_accept[311] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       46,   45,   42,   37,   45,   45,    2,   43,    1,   44,
        5,    8,    9,    7,    6,   11,   12,   10,   39,   39,
       38,   39,   39,   36,   36,   45,   20,   35,   44,    5,
       14,    8,    9,    7,   16,    6,   17,   15,   11,   12,
       10,   18,   32,   45,   35,   45,   20,   31,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       30,   20,   35,   30,   35,   35,   35,   29,   29,   35,

       35,   35,   35,   35,   40,   40,   40,    2,   40,   45,
       45,   33,   35,   34,   34,   35,   35,   35,   34,   35,
       35,   35,    0,    0,   42,   37,    0,    0,   41,   44,
       44,   44,    5,    8,    9,    7,    6,   11,   12,   10,
       38,    0,   36,    0,   21,   21,    0,   21,   20,   21,
       36,   21,   21,   36,   35,   35,   21,   44,    5,   14,
        8,    9,    7,   16,    6,   17,   15,   11,   12,   10,
       18,   32,   24,   21,   20,   21,    0,   21,   21,    0,
       31,   23,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   30,   30,   20,   35,   26,

       30,   29,   35,   27,   35,   35,   29,   35,   33,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   34,   35,
       35,   44,   44,    0,    0,   36,   21,   36,   36,   21,
       36,   36,   21,   44,   21,   21,   44,   44,    0,   21,
        0,    0,   21,    0,    0,   36,   23,   36,   36,   36,
       36,   36,   36,   30,   25,   35,   35,   35,   35,   34,
       34,   35,   35,   34,   35,   44,   44,    0,   21,   19,
       36,   21,   44,   44,   21,   44,   44,   19,    0,   36,
       36,   22,   36,   36,   36,   30,   35,   35,   28,   35,
       44,   44,   19,   19,    0,   44,    4,   36,   36,   22,

       35,   35,   13,   44,   36,   36,   35,   35,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    6,    1,    1,    1,    7,
        7,    8,    9,    7,   10,   11,   12,   13,   14,   14,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
        7,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,    1,   41,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    2,    3,
        1,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5
    } ;

static yyconst short int yy_base[348] =
    {   0,
        0,   12,   52,   58,   70,   84,  125,  137,  149,    0,
      182,    0,  208,    0,  235,    0, 1020, 1019,  263,  289,
      315,  343,  365,    0,  401,  412,  424,  436,  448,    0,
     1054, 1057, 1057,   54,    6, 1050, 1057, 1057, 1057,  137,
        0,    0,    0,    0,    0,    0,    0,    0, 1057, 1057,
      162,   63, 1057,    0,  161,  154,  485,  192,  268,  193,
      247,  274,  284,  299,  305,  322,  328,  336,  350,  356,
      364,  377,    0,   55,  258,  165,  516,    0, 1035,  243,
     1013, 1027, 1032,  145, 1025, 1015, 1031, 1016, 1029, 1028,
      391,  186,  330,  548,  550,  366,  558,  307,  358,  560,

      568,  569,  577,  585, 1057, 1057,  203, 1057, 1057,  408,
      287,    0,    0, 1009,    0, 1007,  569,  581, 1021, 1002,
     1006, 1004,  488,  302, 1057,  530,  317, 1033, 1057,    0,
     1006,  999,    0,    0,    0,    0,    0,    0,    0,    0,
      597,  418,    0,  534,  571,  600, 1005, 1013,    0,    0,
      607,  607,  609,  998,  621,    0,  631,  929,  668,  674,
      680,  686,  692,  698,  704,  710,  716,  722,  728,  734,
      740,    0,  630,  610,    0, 1057,  744,  744,  746,  896,
        0,    0,  900,  883,  885,  886,  879,  886,  885,  882,
      889,  877,  880,  889,  878,  746,  765,  624,  767,  773,

      783,  785,  791,  793,  799,  801,  807,  809,    0,  857,
      855,  862,  293,  849,  854,  361,  839,  834,    0,  847,
      817,  828,  822,  813,  813,  661,  770,  793,  788,  772,
      773,  759,    0,  815,  822,  811,  745,  745,  668,  674,
      726,  726,  713,  715,  709,  701,    0,  685,  663,  650,
      602,  599,  580,  830,  836,  838,  847,  848,  597,    0,
        0,  577,  574,    0,  572,  572,  562,  686,  692,  758,
      547,  698,  549,  545,  535,  535,  529,  859,  525,  513,
      521,    0,  517,  509,  474,  861,  863,  874,  876,  389,
      384,  373,  887,  720,  726,  355,    0,  344,  330,  888,

      890,  326,    0,  302,  316,  288,  891,  266,    0, 1057,
      919,  924,  929,  934,  939,  944,  949,  280,  275,  273,
      253,  246,  182,  176,  172,  164,  953,  957,  961,  965,
      969,  973,  977,  981,  985,  989,  993,  997, 1001, 1005,
     1009, 1012,    6, 1016, 1020, 1023, 1026
    } ;

static yyconst short int yy_def[348] =
    {   0,
      311,  310,  312,  312,  313,  310,  314,  314,  313,    9,
      311,   11,  310,   13,   13,   15,   15,   15,    9,    9,
        9,    9,    9,   23,  315,  315,  316,  316,  310,   29,
      310,  310,  310,  310,  310,  317,  310,  310,  310,  318,
      319,  320,  321,  322,  323,  324,  325,  326,  310,  310,
      310,  310,  310,  327,  327,  310,  310,  328,  318,  329,
      330,  331,  332,  333,  334,  335,  336,  337,  338,  339,
      340,  341,  342,  310,  328,  310,  310,  343,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      344,  327,  328,  345,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  310,  310,  310,  310,  310,  310,
      310,  346,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  310,  310,  310,  310,  310,  317,  310,  318,
      318,  318,  319,  320,  321,  322,  323,  324,  325,  326,
      310,  310,  327,  310,   57,   77,  310,  146,   57,  327,
      327,  327,  152,  327,  328,  347,  310,  318,  329,  330,
      331,  332,  333,  334,  335,  336,  337,  338,  339,  340,
      341,  342,  328,   77,   77,  310,  310,  310,  178,  310,
      343,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  344,  344,  327,  328,  328,

      345,  328,  328,  328,  328,  328,  328,  328,  346,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  318,  318,  310,  310,  327,   57,  327,  327,  327,
      327,  327,  318,  318,  318,  235,  318,  318,  310,  146,
      310,  310,  310,  310,  310,  327,  327,  327,  327,  327,
      327,  327,  327,  344,  328,  328,  328,  328,  347,  347,
      347,  347,  347,  347,  347,  318,  318,  310,  240,  310,
      327,  157,  318,  318,  318,  318,  318,  318,  310,  327,
      327,  327,  327,  327,  327,  344,  328,  328,  328,  347,
      318,  318,  310,  310,  310,  318,  318,  327,  327,  344,

      328,  347,  318,  318,  327,  327,  328,  347,  318,    0,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310
    } ;

static yyconst short int yy_nxt[1099] =
    {   0,
      310,   33,   34,   35,   36,   37,   33,   37,  126,  127,
      181,   38,   32,   33,   34,   35,   36,   37,   33,   39,
       32,   32,   40,   38,   32,   32,   32,   32,   41,   32,
       42,   43,   42,   43,   44,   32,   45,   41,   32,   32,
       32,   32,   32,   41,   46,   32,   32,   44,   47,   48,
       32,   32,   32,   50,   51,   52,  123,  124,   50,   50,
       51,   52,  125,   53,   50,  141,  142,  146,  146,   53,
       32,   33,   34,   35,   54,   37,   33,   37,   55,   55,
       56,   38,   57,   57,   32,   33,   34,   35,   54,   37,
       33,   39,   55,   55,   59,   38,   57,   57,   58,   58,

       60,   61,   62,   63,   62,   63,   64,   65,   66,   60,
       67,   58,   58,   58,   68,   60,   69,   58,   58,   64,
       70,   71,   58,   72,   58,   32,   33,   34,   35,   32,
       37,   33,   37,   32,   32,   32,   38,   32,   33,   34,
       35,   32,   37,   33,   37,   32,   32,   32,   38,   32,
       33,   34,   35,   54,   37,   33,   37,   55,   55,   74,
       38,   57,   57,  131,  123,  124,  146,  146,  140,  132,
      125,  144,  147,  145,  145,  144,  139,  174,  174,  188,
      138,  189,   75,   33,   34,   35,  137,   37,   33,   37,
       76,   76,   74,   38,   77,   77,  143,  143,  198,  198,

      143,  143,  155,  156,  156,  126,  127,   78,   32,   33,
       34,   35,   54,   37,   33,   37,   55,   55,   74,   38,
       57,   57,   79,   54,   54,   80,   81,   54,   54,   54,
       54,   54,   54,   82,   54,   54,   83,   84,   54,   54,
       85,   54,   54,   54,   54,   54,   54,   54,   54,   54,
      136,  143,   54,   54,   86,  143,  155,  135,  156,  182,
       87,  183,  143,   54,   88,  184,  143,   54,   89,  156,
       90,   54,   54,   32,  173,   92,   92,  134,  143,  133,
      157,  157,  143,  155,  130,  156,  158,  264,  143,  123,
      124,   93,  143,  155,  131,  156,   58,   54,   54,   32,

      132,   92,   92,  143,  123,  124,  282,  143,  155,  143,
      156,  143,  261,  143,  155,  143,  156,   93,  156,  126,
      127,  262,   58,   54,   54,   32,  143,   92,   92,  182,
      143,  155,  143,  156,  143,  309,  143,  155,  143,  156,
      143,  156,  308,   93,  143,  155,  306,  156,   58,  199,
       94,   54,   54,   32,  143,   92,   92,  200,  143,  155,
      143,  156,  143,  305,  143,  155,  143,  156,  143,  156,
      143,   93,  143,  155,  143,  156,   58,  156,   94,   95,
      261,  143,   96,  233,  203,  143,  155,   97,  156,  263,
       98,   99,  100,  101,  102,  143,  103,  304,  104,  143,

      143,   98,  106,   34,  107,  197,  108,  106,  108,  303,
      123,  124,  109,  106,   34,  107,  125,  108,  106,  108,
      141,  142,  302,  109,   32,   33,  110,  111,   32,   37,
       33,   37,   32,   32,   32,   38,   32,   33,  110,  111,
       32,   37,   33,   37,   32,   32,   32,   38,   32,   33,
      110,  111,   32,   37,   33,   37,   32,   32,   32,   38,
       32,   32,  113,  113,  114,  115,  113,  113,  113,  113,
      113,  113,  113,  116,  113,  117,  113,  118,  113,  119,
      120,  113,  121,  122,  113,  113,  113,  113,  113,  143,
      123,  124,  282,  143,  143,  148,  125,  149,  149,  150,

      143,  143,  143,  151,  152,  152,  150,  143,  143,  152,
      143,  153,  152,  154,  152,  143,  143,  150,  152,  152,
      150,  143,  143,  143,  143,  143,  148,  282,  175,  175,
      176,  299,  123,  124,  177,  178,  178,  176,  125,  247,
      178,  298,  179,  178,  180,  178,  146,  146,  176,  178,
      178,  176,  143,  176,  143,  233,  143,  155,  143,  156,
      235,  156,  143,  233,  143,  235,  143,  202,  143,  156,
      296,  156,  143,  143,  204,  150,  143,  143,  292,  156,
      156,  143,  202,  145,  145,  143,  202,  199,  156,  143,
      291,  205,  212,  143,  290,  213,  156,  206,  214,  123,

      124,  202,  207,  208,  215,  125,  261,  216,  217,  261,
      310,  219,  146,  146,  285,  226,  226,  207,  224,  227,
      227,  150,  174,  174,  284,  143,  150,  229,  150,  143,
      230,  231,  156,  228,  143,  154,  198,  198,  143,  150,
      282,  156,  150,  157,  157,  233,  130,  130,  130,  234,
      235,  235,  233,  130,  130,  235,  130,  236,  235,  237,
      235,  130,  130,  233,  235,  235,  233,  130,  130,  130,
      130,  130,  143,  227,  227,  283,  143,  155,  143,  156,
      240,  240,  143,  155,  143,  156,  240,  240,  143,  155,
      143,  156,  310,  282,  143,  155,  143,  156,  269,  269,

      143,  155,  143,  156,  269,  269,  143,  155,  143,  156,
      272,  272,  143,  155,  143,  156,  130,  281,  143,  155,
      143,  156,  294,  295,  143,  155,  143,  156,  294,  295,
      143,  155,  143,  156,  280,  176,  143,  155,  143,  156,
      178,  176,  143,  155,  143,  156,  178,  279,  143,  155,
      143,  156,  239,  239,  143,  143,  240,  240,  176,  293,
      294,  295,  278,  176,  242,  176,  277,  243,  244,  143,
      241,  143,  180,  143,  143,  143,  176,  143,  156,  176,
      310,  143,  227,  227,  156,  150,  255,  143,  143,  143,
      254,  143,  155,  143,  156,  143,  156,  143,  152,  143,

      150,  143,  156,  143,  156,  143,  256,  143,  152,  143,
      156,  143,  156,  143,  271,  143,  202,  143,  156,  257,
      156,  268,  268,  268,  268,  269,  269,  272,  272,  274,
      270,  202,  275,  276,  143,  258,  233,  267,  143,  143,
      143,  233,  143,  233,  143,  266,  143,  156,  273,  156,
      237,  143,  143,  265,  233,  143,  143,  233,  156,  156,
      293,  294,  295,  219,  286,  143,  264,  143,  260,  143,
      143,  143,  287,  260,  156,  288,  260,  289,  143,  300,
      143,  260,  143,  202,  143,  156,  259,  156,  293,  294,
      295,  297,  143,  219,  143,  143,  143,  143,  143,  143,

      301,  156,  156,  253,  252,  251,  250,  249,  207,  247,
      247,  248,  182,  182,  247,  246,  182,  245,  307,   32,
       32,   32,   32,   32,   49,   49,   49,   49,   49,   58,
       58,   58,   58,   58,   73,   73,   73,   73,   73,  105,
      105,  105,  105,  105,  112,  112,  112,  112,  112,  128,
      128,  128,  128,  128,  143,  143,  238,  143,  155,  155,
      155,  155,  159,  159,  159,  159,  160,  160,  160,  160,
      161,  161,  161,  161,  162,  162,  162,  162,  163,  163,
      163,  163,  164,  164,  164,  164,  165,  165,  165,  165,
      166,  166,  166,  166,  167,  167,  167,  167,  168,  168,

      168,  168,  169,  169,  169,  169,  170,  170,  170,  170,
      171,  171,  171,  171,  172,  172,  172,  196,  196,  232,
      196,  201,  201,  201,  201,  209,  209,  209,  156,  156,
      156,  310,  225,  223,  222,  129,  221,  220,  219,  218,
      211,  210,  195,  194,  193,  192,  191,  190,  187,  186,
      185,  182,  129,  310,   91,   91,   31,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310

    } ;

static yyconst short int yy_chk[1099] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    1,   35,   35,
      343,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    3,    3,    3,   34,   34,    3,    4,
        4,    4,   34,    3,    4,   52,   52,   74,   74,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   40,   51,   51,   56,   56,  326,   40,
       51,   55,   56,   55,   55,   76,  325,   76,   76,   84,
      324,   84,    9,   11,   11,   11,  323,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   58,   60,   92,   92,

       58,   60,   60,   58,   60,  107,  107,   11,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
      322,   61,   15,   15,   15,   61,   61,  321,   61,   80,
       15,   80,   75,   15,   15,   80,   75,   15,   15,   75,
       15,   19,   19,   19,   75,   19,   19,  320,   62,  319,
       59,   59,   62,   62,  318,   62,   59,  308,   63,  111,
      111,   19,   63,   63,   59,   63,   19,   20,   20,   20,

       59,   20,   20,   64,  124,  124,  306,   64,   64,   65,
       64,   98,  213,   65,   65,   98,   65,   20,   98,  127,
      127,  213,   20,   21,   21,   21,   66,   21,   21,  305,
       66,   66,   67,   66,   93,  304,   67,   67,   93,   67,
       68,   93,  302,   21,   68,   68,  299,   68,   21,   93,
       21,   22,   22,   22,   69,   22,   22,   93,   69,   69,
       70,   69,   99,  298,   70,   70,   99,   70,   71,   99,
       96,   22,   71,   71,   96,   71,   22,   96,   22,   23,
      216,   72,   23,  296,   96,   72,   72,   23,   72,  216,
       23,   23,   23,   23,   23,   91,   23,  292,   23,   91,

       91,   23,   25,   25,   25,   91,   25,   25,   25,  291,
      110,  110,   25,   26,   26,   26,  110,   26,   26,   26,
      142,  142,  290,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   57,
      123,  123,  285,   57,   57,   57,  123,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   77,  284,   77,   77,
       77,  283,  126,  126,   77,   77,   77,   77,  126,  281,
       77,  280,   77,   77,   77,   77,  144,  144,   77,   77,
       77,   77,   94,  279,   95,  277,   94,   94,   95,   94,
      276,   95,   97,  275,  100,  274,   97,   95,  100,   97,
      273,  100,  101,  102,   97,  271,  101,  102,  267,  101,
      102,  103,   95,  145,  145,  103,  102,  101,  103,  104,
      266,  100,  117,  104,  265,  117,  104,  103,  117,  141,

      141,  102,  104,  104,  118,  141,  263,  118,  118,  262,
      146,  259,  146,  146,  253,  151,  151,  104,  146,  151,
      151,  152,  174,  174,  252,  155,  152,  153,  152,  155,
      153,  153,  155,  152,  173,  152,  198,  198,  173,  152,
      251,  173,  152,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  159,  226,  226,  250,  159,  159,  160,  159,
      239,  239,  160,  160,  161,  160,  240,  240,  161,  161,
      162,  161,  240,  249,  162,  162,  163,  162,  268,  268,

      163,  163,  164,  163,  269,  269,  164,  164,  165,  164,
      272,  272,  165,  165,  166,  165,  272,  248,  166,  166,
      167,  166,  294,  294,  167,  167,  168,  167,  295,  295,
      168,  168,  169,  168,  246,  245,  169,  169,  170,  169,
      244,  243,  170,  170,  171,  170,  242,  241,  171,  171,
      196,  171,  177,  177,  196,  196,  177,  177,  178,  270,
      270,  270,  238,  178,  179,  178,  237,  179,  179,  197,
      178,  199,  178,  197,  197,  199,  178,  200,  199,  178,
      227,  200,  227,  227,  200,  232,  199,  201,  227,  202,
      197,  201,  201,  202,  201,  203,  202,  204,  231,  203,

      230,  204,  203,  205,  204,  206,  203,  205,  229,  206,
      205,  207,  206,  208,  228,  207,  205,  208,  207,  206,
      208,  224,  224,  234,  234,  224,  224,  234,  234,  236,
      225,  205,  236,  236,  254,  208,  235,  223,  254,  254,
      255,  235,  256,  235,  255,  222,  256,  255,  235,  256,
      235,  257,  258,  221,  235,  257,  258,  235,  257,  258,
      278,  278,  278,  220,  254,  286,  218,  287,  217,  286,
      286,  287,  256,  215,  287,  257,  214,  258,  288,  286,
      289,  212,  288,  287,  289,  288,  211,  289,  293,  293,
      293,  278,  300,  210,  301,  307,  300,  300,  301,  307,

      288,  301,  307,  195,  194,  193,  192,  191,  307,  190,
      189,  188,  187,  186,  185,  184,  183,  180,  301,  311,
      311,  311,  311,  311,  312,  312,  312,  312,  312,  313,
      313,  313,  313,  313,  314,  314,  314,  314,  314,  315,
      315,  315,  315,  315,  316,  316,  316,  316,  316,  317,
      317,  317,  317,  317,  327,  327,  158,  327,  328,  328,
      328,  328,  329,  329,  329,  329,  330,  330,  330,  330,
      331,  331,  331,  331,  332,  332,  332,  332,  333,  333,
      333,  333,  334,  334,  334,  334,  335,  335,  335,  335,
      336,  336,  336,  336,  337,  337,  337,  337,  338,  338,

      338,  338,  339,  339,  339,  339,  340,  340,  340,  340,
      341,  341,  341,  341,  342,  342,  342,  344,  344,  154,
      344,  345,  345,  345,  345,  346,  346,  346,  347,  347,
      347,  148,  147,  132,  131,  128,  122,  121,  120,  119,
      116,  114,   90,   89,   88,   87,   86,   85,   83,   82,
       81,   79,   36,   31,   18,   17,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\spice.l"
#define INITIAL 0
#line 2 ".\\spice.l"
#include "spice.tab.hpp"
#include <string>
#include <string.h>
#include <stdio.h>
#define YY_NEVER_INTERACTIVE 1
using namespace std;
/* Source functions */
/* Device Models */
/* MOS specific device properties */
/* analog behavioural */
#define COMMENT 1
#define STARTUP 2
#define SUBCKT 3
#define RLCPROP 4
#define LREF 5
#define FUNREF 6
#define GEVALS 7
#define FHVALS 8
#define VSWITCH 9
#define ISWITCH 10
#define DEVPROP 11
#define IGNORE 12
 
#define MODREF1 13
#define MODREF2 14

#line 742 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 55 ".\\spice.l"

#line 898 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1057 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 56 ".\\spice.l"
{ /* ignored region begins here */  BEGIN(COMMENT);  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 ".\\spice.l"
{
					    /* ignored inline region begins here (3f5, 2g6 and hspice) */
					    BEGIN(IGNORE);
					  	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 ".\\spice.l"
{
	    		/* subcircuit definition start */
	    		BEGIN(SUBCKT);
	    		yylval.str = NULL;
	    		return SUBCKT_Action;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 ".\\spice.l"
{ 
				/* subcircuit definition end */
	    		BEGIN(SUBCKT);
	    		yylval.str = NULL;
	    		return ENDS_Action;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 ".\\spice.l"
{ 
				/* R, L and C instances */
				BEGIN(RLCPROP);
				yylval.str = strdup(yytext);
				return RLC_Device;
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 ".\\spice.l"
{ 
				/* Mutual inductor instances */
    			BEGIN(LREF);
    			yylval.str = strdup(yytext);
    			return K_Device;
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 85 ".\\spice.l"
{
    			/* voltage and current source instances */
			    BEGIN(FUNREF);
			    yylval.str = strdup(yytext);
			    return IV_Source;
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 ".\\spice.l"
{
			    /* voltage controlled source instances */
			    BEGIN(GEVALS);
			    yylval.str = strdup(yytext);
			    return GE_Source;
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 ".\\spice.l"
{
			    /* current controlled source instances */
			    BEGIN(FHVALS);
			    yylval.str = strdup(yytext);
			    return FH_Source;
				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 103 ".\\spice.l"
{ 
				/* subcircuit instances */
			    BEGIN(STARTUP);
			    yylval.str = strdup(yytext);
			    return X_Device;
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 ".\\spice.l"
{ 
				/* voltage controlled switch */
			    BEGIN(VSWITCH);
			    yylval.str = strdup(yytext);
			    return S_Device;
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 ".\\spice.l"
{ 
				/* current controlled switch */
			    BEGIN(ISWITCH);
			    yylval.str = strdup(yytext);
			    return W_Device;
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 121 ".\\spice.l"
{ 
				/* device Model definitions */
			    BEGIN(MODREF1);
			    yylval.str = NULL;
			    return MODEL_Action;
				}			
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 ".\\spice.l"
{ 
				/* diode instances */				    
			    BEGIN(DEVPROP);
			    yylval.str = strdup(yytext);
			    return Diode_Device;
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 ".\\spice.l"
{ 
				/* BJT instances */				    
			    BEGIN(DEVPROP);
			    yylval.str = strdup(yytext);
			    return Bipolar_Device;
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 139 ".\\spice.l"
{ 
				/* JFET instances */				    
			    BEGIN(DEVPROP);
			    yylval.str = strdup(yytext);
			    return JFET_Device;
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 ".\\spice.l"
{ 
				/* MOSFET instances */				    
			    BEGIN(DEVPROP);
			    yylval.str = strdup(yytext);
			    return MOSFET_Device;
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 151 ".\\spice.l"
{ 
				/* MESFET instances */				    
			    BEGIN(DEVPROP);
			    yylval.str = strdup(yytext);
			    return MESFET_Device;
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 158 ".\\spice.l"
{ 
				/* identify end of netlist */
				yylval.str = NULL;
				return End;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 163 ".\\spice.l"
{
				/* identify node (containing digits) */
				yylval.str = strdup(yytext);
				return Digits;
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 168 ".\\spice.l"
{
			    /* identify float (any kind) */
			    yylval.str = NULL;
			    return Floats;
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 ".\\spice.l"
{
				/* identify analog behaviour */
				BEGIN(IGNORE);
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 178 ".\\spice.l"
{ 
				/* function specials (e.g. in sources) */
				yylval.str = NULL;
    			return Function;
				}									
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 183 ".\\spice.l"
{ 
				/* a TC special */
				yylval.str = NULL;
				return TC_Special;
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 188 ".\\spice.l"
{ 
				/* a device special */
				yylval.str = NULL;
    		    return OFF_Special;
				}		
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 193 ".\\spice.l"
{ 
				/* a device special */
				yylval.str = NULL;
    			return ON_Special;
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 198 ".\\spice.l"
{ 
				/* another device special */
				yylval.str = NULL;
    			return IC_Special;
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 203 ".\\spice.l"
{ 
				/* another device special */
				yylval.str = NULL;
    			return TEMP_Special;
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 208 ".\\spice.l"
{ 
				/* another device special */
				yylval.str = NULL;
    			return MOS_Special;
				}							
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 213 ".\\spice.l"
{ 
				/* voltage source references */
				yylval.str = NULL;
			    return V_Source;
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 218 ".\\spice.l"
{ 
				/* inductor references */
				yylval.str = strdup(yytext);
				return L_Device;
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 223 ".\\spice.l"
{ 
				/* arbitrary identifier */
			    BEGIN(STARTUP);
			    yylval.str = strdup(yytext);
			    return Identifier;
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 229 ".\\spice.l"
{ 
				/* arbitrary identifier */
    			BEGIN(MODREF2);
    			yylval.str = NULL;
    			return Identifier;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 235 ".\\spice.l"
{ 
				/* Model specification specials */
    			BEGIN(STARTUP);
    			yylval.str = NULL;
    			return MODEL_Spec;
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 241 ".\\spice.l"
{ 
				/* arbitrary identifier */
				yylval.str = strdup(yytext);
				return Identifier;
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 246 ".\\spice.l"
{
    			/* identify node */
    			yylval.str = strdup(yytext);
    			return Nodes;
				}						
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 251 ".\\spice.l"
{ 
				/* skipping ends here */ 
				BEGIN(STARTUP);  
				yylval.str = NULL;
				return Eol;
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 257 ".\\spice.l"
{ BEGIN(STARTUP);
				/* skipping ends here */ 
				}				
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 260 ".\\spice.l"
{ /* skip any character in here */ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 261 ".\\spice.l"
{ /* skip any character in here */ }
	YY_BREAK
case 41:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 262 ".\\spice.l"
{ /* any thing after '#' is a comment */ }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 263 ".\\spice.l"
{
				/* skip spaces, '=', '(', ')', ',' and the leading '+' */
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 266 ".\\spice.l"
{/* skip '/' */}				
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 267 ".\\spice.l"
{ 
				/* skipping unknow command */ 
				BEGIN(IGNORE); 
				}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 271 ".\\spice.l"
ECHO;
	YY_BREAK
#line 1379 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STARTUP):
case YY_STATE_EOF(SUBCKT):
case YY_STATE_EOF(RLCPROP):
case YY_STATE_EOF(LREF):
case YY_STATE_EOF(FUNREF):
case YY_STATE_EOF(GEVALS):
case YY_STATE_EOF(FHVALS):
case YY_STATE_EOF(VSWITCH):
case YY_STATE_EOF(ISWITCH):
case YY_STATE_EOF(DEVPROP):
case YY_STATE_EOF(IGNORE):
case YY_STATE_EOF(MODREF1):
case YY_STATE_EOF(MODREF2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 271 ".\\spice.l"


int prepare(string filename) {
    if ( (yyin = fopen(filename.c_str(),"r")) == 0 ) {
        perror(filename.c_str());
        exit(1);
    }
    return 0;
}

int yywrap() {
	return 1;
}